# Generated by Django 3.2.5 on 2021-07-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsncomments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default=1, max_length=1800),
            preserve_default=False,
        ),
    ]
